quarkus.datasource.db-kind = h2 
quarkus.datasource.username = hibernate
quarkus.datasource.password = hibernate
quarkus.datasource.jdbc.url = jdbc:h2:mem:UniDemo;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create 

# Customer
quarkus.cache.caffeine.customer-by-id.maximum-size=10_000
quarkus.cache.caffeine.customer-by-id.expire-after-write=60S
quarkus.cache.caffeine.customers-list.maximum-size=2_000
quarkus.cache.caffeine.customers-list.expire-after-write=15S

# Device
quarkus.cache.caffeine.device-by-id.maximum-size=10_000
quarkus.cache.caffeine.device-by-id.expire-after-write=60S
quarkus.cache.caffeine.devices-list.maximum-size=2_000
quarkus.cache.caffeine.devices-list.expire-after-write=15S

# Order
quarkus.cache.caffeine.order-by-id.maximum-size=10_000
quarkus.cache.caffeine.order-by-id.expire-after-write=60S
quarkus.cache.caffeine.orders-list.maximum-size=2_000
quarkus.cache.caffeine.orders-list.expire-after-write=15S
